name: school_tracking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  keyboard_utils: ^1.2.4
  sailor: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
  - family: MontserratLight
    fonts:
      - asset: lib/assets/fonts/Montserrat-Light.ttf
  - family: MontserratRegular
    fonts:
      - asset: lib/assets/fonts/Montserrat-Regular.ttf
  - family: MontserratMedium
    fonts:
      - asset: lib/assets/fonts/Montserrat-Medium.ttf
  - family: MontserratMediumItalic
    fonts:
      - asset: lib/assets/fonts/Montserrat-Medium-Italic.ttf
  - family: MontserratSemiBold
    fonts: 
      - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
  - family: MontserratBold
    fonts: 
      - asset: lib/assets/fonts/Montserrat-Bold.ttf

